[package]
name = "newsletter-rs"
version = "0.1.0"

edition = "2021"

[dependencies]
axum = "0.8"  
eyre = "0.6"  # For convinient error handling  
tokio = { version = "1", features = ["full"] }  
post_scanner = "0.3.0"

[dev-dependencies]
