[package]
name = "newsletter-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
axum = "0.8.3"
eyre = "0.6"  # Error handling library
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"  # For parsing form data
sqlx = { version = "0.8.0", features = ["postgres", "runtime-tokio-native-tls", "macros"], default-features = false }
tokio = { version = "1", features = ["full"] }
tower = "0.5.2"
tracing = "0.1"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1.1", features = ["full"] }
testcontainers-rs = "0.0.1"
http-body-util = "0.1.1"


[package.metadata.cargo-machete]
ignored = [
    "hyper",        # Used by axum
    "hyper-util",   # Used by axum
    "reqwest",      # Used in tests
    "serde_urlencoded", # Used for form data parsing
    "tokio-test",   # Used in tests
    "tracing"       # Used for logging
]
