[package]
name = "newsletter-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8"  
eyre = "0.6"  # For convinient error handling  
serde = "1.0.219"
sqlx = { version = "0.8.3", features = ["postgres"] }
tokio = { version = "1", features = ["full"] }  

[dev-dependencies]
