[package]
name = "newsletter-rs"
version = "0.1.0"
edition = "2021"

[dependencies] 
dotenvy = "0.15.7"
eyre = "0.6"  # For convinient error handling  
sqlx = { version = "0.8.0", features = ["postgres", "runtime-tokio-native-tls"], default-features = false }
tokio = { version = "1", features = ["full"] }  
axum = "0.8.3"
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
tower = "0.5.2"
tracing = "0.1"
validator = { version = "0.16", features = ["derive"] }
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1.1", features = ["full"] }
http-body-util = "0.1.1"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio-test = "0.4"
