[package]
name = "newsletter-rs"
version = "0.1.0"
edition = "2021"

[dependencies] 
dotenvy = "0.15.7"
eyre = "0.6"  # For convinient error handling  
sqlx = { version = "0.8.0", features = ["postgres", "runtime-tokio-native-tls", "macros", "uuid"], default-features = false }
tokio = { version = "1", features = ["full"] }  
axum = "0.8.3"
serde = { version = "1", features = ["derive"] }
tower = "0.5.2"
tracing = "0.1"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1.1", features = ["full"] }
http-body-util = "0.1.1"
testcontainers-rs = "0.0.1"
chrono = { version = "0.4.41", features = ["serde"] }
regex = "1"
lazy_static="1.4.0"
uuid = {version = "1.16.0",features = ["v4"]}

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio-test = "0.4"

[package.metadata.cargo-machete]
ignored = [
    "hyper",        # Used by axum
    "hyper-util",   # Used by axum
    "reqwest",      # Used in tests
    "serde_urlencoded", # Used for form data parsing
    "tokio-test",   # Used in tests
    "tracing"       # Used for logging
]
