name: CI Pipeline

on:
  pull_request:

jobs:
  ci-checks:
    name: Run CI checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Optimize Build Performance
        uses: rui314/setup-mold@v1
      
      - name: Format Check
        run: cargo fmt --all --check

      - name: Cargo Build
        run: cargo build --all-features --all-targets

      - name: Cargo test
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - run: cargo nextest run --all-features --all-targets

      - name: Run Documentation Tests
        run: cargo test --doc --all-features

      - name: Check for unused dependencies
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete
          args: check --with-metadata
      
      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Run Code Coverage with cargo-tarpaulin
        run: |
          cargo tarpaulin --out Html --fail-under 70

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: tarpaulin-report.html
          
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - run: cargo audit
