name: CI Pipeline

on:
  pull_request:

jobs:
  ci-checks:
    name: Run CI checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Optimize Build Performance
        uses: rui314/setup-mold@v1

      - name: Install Tools
        uses: taiki-e/install-action@v2
        with:
          tool: |
            nextest
            cargo-machete
            cargo-audit

      - name: Format Check
        run: cargo fmt --all --check

      - name: Cargo Build
        run: cargo build --all-features --all-targets

      - name: Cargo test
        run: cargo nextest run --all-features --all-targets

      - name: Run Documentation Tests
        run: cargo test --doc --all-features

      - name: Check for unused dependencies
        run: cargo machete check --fail --with-metadata

  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run Cargo Audit
        run: cargo audit
